package com.chinatelecom.ismp.sp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-21T11:35:41.903+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://sp.ismp.chinatelecom.com", name = "IsmpSpEngine")
@XmlSeeAlso({com.chinatelecom.ismp.sp.req.ObjectFactory.class, com.chinatelecom.ismp.sp.rsp.ObjectFactory.class, ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IsmpSpEngine {

    @WebResult(name = "spWithdrawSubscriptionReturn", targetNamespace = "http://sp.ismp.chinatelecom.com", partName = "spWithdrawSubscriptionReturn")
    @WebMethod
    public com.chinatelecom.ismp.sp.rsp.Response spWithdrawSubscription(
            @WebParam(partName = "spWithdrawSubscriptionReqPara", name = "spWithdrawSubscriptionReqPara", targetNamespace = "http://sp.ismp.chinatelecom.com")
            com.chinatelecom.ismp.sp.req.SPWithdrawSubscriptionReq spWithdrawSubscriptionReqPara
    );

    @WebResult(name = "orderRelationUpdateNotifyReturn", targetNamespace = "http://sp.ismp.chinatelecom.com", partName = "orderRelationUpdateNotifyReturn")
    @WebMethod
    public com.chinatelecom.ismp.sp.rsp.Response orderRelationUpdateNotify(
            @WebParam(partName = "orderRelationUpdateNotifyReq", name = "orderRelationUpdateNotifyReq", targetNamespace = "http://sp.ismp.chinatelecom.com")
            com.chinatelecom.ismp.sp.req.OrderRelationUpdateNotifyReq orderRelationUpdateNotifyReq
    );

    @WebResult(name = "serviceConsumeNotifyReturn", targetNamespace = "http://sp.ismp.chinatelecom.com", partName = "serviceConsumeNotifyReturn")
    @WebMethod
    public com.chinatelecom.ismp.sp.rsp.Response serviceConsumeNotify(
            @WebParam(partName = "serviceConsumeNotifyReqPara", name = "serviceConsumeNotifyReqPara", targetNamespace = "http://sp.ismp.chinatelecom.com")
            com.chinatelecom.ismp.sp.req.ServiceConsumeNotifyReq serviceConsumeNotifyReqPara
    );

    @WebResult(name = "notifyManagementInfoReturn", targetNamespace = "http://sp.ismp.chinatelecom.com", partName = "notifyManagementInfoReturn")
    @WebMethod
    public com.chinatelecom.ismp.sp.rsp.NotifyManagementInfoRsp notifyManagementInfo(
            @WebParam(partName = "notifyManagementInfoReq", name = "notifyManagementInfoReq", targetNamespace = "http://sp.ismp.chinatelecom.com")
            com.chinatelecom.ismp.sp.req.NotifyManagementInfoReq notifyManagementInfoReq
    );
}
