
package com.chinatelecom.ismp.sp;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-21T11:35:41.919+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class IsmpSpEngine_IsmpSpEngine_Server{

    protected IsmpSpEngine_IsmpSpEngine_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IsmpSpEngineImpl();
        String address = "http://localhost:8383/WsdlProject/services/IsmpSpEngine";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new IsmpSpEngine_IsmpSpEngine_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
