
package cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-21T15:21:10.044+08:00
 * Generated source version: 3.0.1
 * 
 */
 
public class SmsNotification_SmsNotification_Server{

    protected SmsNotification_SmsNotification_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new SmsNotificationImpl();
        String address = "http://localhost:9080/SmsNotificationService/services/SmsNotification";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception {
        new SmsNotification_SmsNotification_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
