
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface;

import cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryStatus;
import com.sun.java.swing.plaf.motif.resources.motif;
import com.sun.jndi.url.corbaname.corbanameURLContextFactory;
import com.temobi.oface.common.db.SmsDbHelper;
import com.temobi.oface.common.util.DateConvert;
import com.temobi.oface.common.util.SysLog;

import java.util.Date;
import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-21T15:21:10.012+08:00
 * Generated source version: 3.0.1
 * 
 */

@WebService(
                      serviceName = "SmsNotificationService",
                      portName = "SmsNotification",
                      targetNamespace = "http://www.chinatelecom.com.cn/wsdl/ctcc/sms/notification/v2_1/service",
                      wsdlLocation = "/wsdl/ctcc_sms_notification_service_2_1.wsdl",
                      endpointInterface = "cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface.SmsNotification")
                      
public class SmsNotificationImpl implements SmsNotification {

    private static final Logger LOG = Logger.getLogger(SmsNotificationImpl.class.getName());

    /* 网关将短消息递交状态报告给应用
     * @see cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface.SmsNotification#notifySmsDeliveryReceipt(java.lang.String  correlator ,)cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryInformation  deliveryStatus )*
     */
    public void notifySmsDeliveryReceipt(String correlator,cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryInformation deliveryStatus) {
        SysLog.wsInfo("Executing SmsNotificationImpl.notifySmsDeliveryReceipt...");
        try {
            SysLog.wsInfo("[nsdr] - notifySmsDeliveryReceipt--->correlator:" + correlator + "," + deliveryStatus.toJson());
            if(correlator != null && !"".equals(correlator.trim())){
                correlator = correlator.trim();
                String mobile = deliveryStatus.getAddress();
                if(mobile.startsWith("tel:")){
                    mobile = mobile.substring(mobile.indexOf(":") + 1);
                }
                String deliveryStat= deliveryStatus.getDeliveryStatus().value();
                if(deliveryStat.equals(DeliveryStatus.DELIVERED_TO_TERMINAL.value())){
                    deliveryStat = "DELIVRD";
                }

//                http://218.204.254.238/oface/ws/chinatelecom/smsNotification
                Date submitTime = DateConvert.convertS2Date(correlator,"yyyyMMddHHmmss");
                int i = SmsDbHelper.getSmssended(correlator, mobile);
                if(i > 0){
                    SmsDbHelper.updateSmssended(submitTime, mobile, deliveryStat);
                }
                SysLog.wsInfo("[nsdr] - notifySmsDeliveryReceipt--->correlator:" + correlator + ",deliveryStat:" + deliveryStat + ",i:" + i + "," + deliveryStatus.toJson());

            }
        } catch (Exception ex) {
            SysLog.error("[nsdr] - notifySmsDeliveryReceipt error" , ex);
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* 网关将发送到特定地址的短消息告知应用
     * @see cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface.SmsNotification#notifySmsReception(java.lang.String  registrationIdentifier ,)cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsMessage  message )*
     */
    public void notifySmsReception(String registrationIdentifier,cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsMessage message) {
        SysLog.wsInfo("Executing notifySmsReception.notifySmsReception...");
        try {
            SysLog.wsInfo("[nsr] - notifySmsReception--->registrationIdentifier:" + registrationIdentifier + "," + message.toJson());
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
