
package cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1._interface;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import cn.com.chinatelecom.wsdl.ctcc.sms.notification.v2_1.service.SmsNotificationService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-21T15:21:09.966+08:00
 * Generated source version: 3.0.1
 * 
 */
public final class SmsNotification_SmsNotification_Client {

    private static final QName SERVICE_NAME = new QName("http://www.chinatelecom.com.cn/wsdl/ctcc/sms/notification/v2_1/service", "SmsNotificationService");

    private SmsNotification_SmsNotification_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = SmsNotificationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        SmsNotificationService ss = new SmsNotificationService(wsdlURL, SERVICE_NAME);
        SmsNotification port = ss.getSmsNotification();  
        
        {
        System.out.println("Invoking notifySmsDeliveryReceipt...");
        String _notifySmsDeliveryReceipt_correlator = "";
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.DeliveryInformation _notifySmsDeliveryReceipt_deliveryStatus = null;
        port.notifySmsDeliveryReceipt(_notifySmsDeliveryReceipt_correlator, _notifySmsDeliveryReceipt_deliveryStatus);


        }
        {
        System.out.println("Invoking notifySmsReception...");
        String _notifySmsReception_registrationIdentifier = "";
        cn.com.chinatelecom.schema.ctcc.sms.v2_1.SmsMessage _notifySmsReception_message = null;
        port.notifySmsReception(_notifySmsReception_registrationIdentifier, _notifySmsReception_message);


        }

        System.exit(0);
    }

}
